### ISSUE TITLE
Internal error while creating updates: 'fiData'

### ISSUE THREAD

**Issue by apiology** [jprouty/mint-amazon-tagger#109]
I'm getting this error using 1.49 - let me know what debugging information I can provide:

Note: My mint account uses the new UI with the navigation on the left hand side; I'm using mintapi 2.1.

```sh
$ mint-amazon-tagger-go
Running version 1.49
You may be asked for an auth code at the command line! Be sure to press ENTER after typing the 6 digit code.
Creating a new webdriver
Navigating to Mint homepage.
Clicking "Sign in" button.
Mint Login Flow: Selecting username from multi-account selector.
Mint Login Flow: Entering password in MFA input
Mint Login Flow: Submitting credentials for MFA
Mint login successful.
Getting Mint categories.
Getting all Mint transactions since 2022-01-02 to None.
Internal error while creating updates: 'fiData'
Traceback (most recent call last):
  File "/Users/broz/.pyenv/versions/3.10.4/envs/filer-for-asana-3.10.4/lib/python3.10/site-packages/mintamazontagger/main.py", line 629, in create_updates
    self.do_create_updates(args, parent)
  File "/Users/broz/.pyenv/versions/3.10.4/envs/filer-for-asana-3.10.4/lib/python3.10/site-packages/mintamazontagger/main.py", line 685, in do_create_updates
    results = tagger.create_updates(
  File "/Users/broz/.pyenv/versions/3.10.4/envs/filer-for-asana-3.10.4/lib/python3.10/site-packages/mintamazontagger/tagger.py", line 144, in create_updates
    mint_trans = mint.Transaction.parse_from_json(
  File "/Users/broz/.pyenv/versions/3.10.4/envs/filer-for-asana-3.10.4/lib/python3.10/site-packages/mintamazontagger/mint.py", line 164, in parse_from_json
    result.append(cls(raw_dict))
  File "/Users/broz/.pyenv/versions/3.10.4/envs/filer-for-asana-3.10.4/lib/python3.10/site-packages/mintamazontagger/mint.py", line 101, in __init__
    self.__dict__.update(pythonify_mint_transaction_dict(raw_dict))
  File "/Users/broz/.pyenv/versions/3.10.4/envs/filer-for-asana-3.10.4/lib/python3.10/site-packages/mintamazontagger/mint.py", line 61, in pythonify_mint_transaction_dict
    raw_dict['fiData'] = FinancialInstitutionData(raw_dict['fiData'])
KeyError: 'fiData'
Internal error while creating updates: 'fiData'
$
```

**Comment by jprouty** [comment]
I wasn't feeling confident that I'd be able to reproduce this error... until I accidentally did today. This happens for transactions that are user entered and therefore do not have an fiData object. Since these transactions aren't candidates for amazon payments in the first place, I've removed these from consideration by the tagger tool. Please try again in 1.52 and reopen this issue if you continue to have trouble. Thanks for reporting!

**Comment by apiology** [comment]
Great success!  Thank you so much, @jprouty.
