### ISSUE TITLE
'Order' object has no attribute 'to_mint_transaction'

### ISSUE THREAD

**Issue by ron23** [jprouty/mint-amazon-tagger#121]
Behavior observed: 
everything worked first time, but then I had unmatched, so I changed from 3 to 7 days for shipping and ran it again.
This time it went straight to Mint and skipped amazon but then got the following error when it started (after login to mint)

Expected behavior: 

Please attach your log file: /Users/ron/MintAmazonTagger/Tagger Logs/2022-11-05_14-33-05.log
[2022-11-05_14-33-05.log](https://github.com/jprouty/mint-amazon-tagger/files/9944773/2022-11-05_14-33-05.log)

<img width="650" alt="image" src="https://user-images.githubusercontent.com/5150512/200143039-49a73342-43d4-4327-99a4-71ae764f4a14.png">

**Comment by jprouty** [comment]
Pasting the stack trace for ease of retrieval. Thanks for the report and sorry for the delay. Are you still having issues?

```
2022-11-05 14:57:19,705 ERROR __main__: Internal error while creating updates: 'Order' object has no attribute 'to_mint_transaction'
Traceback (most recent call last):
  File "mintamazontagger/main.py", line 653, in create_updates
  File "mintamazontagger/main.py", line 709, in do_create_updates
  File "mintamazontagger/tagger.py", line 154, in create_updates
  File "mintamazontagger/tagger.py", line 359, in get_mint_updates
AttributeError: 'Order' object has no attribute 'to_mint_transaction'
```
