### ISSUE TITLE
Order CSV is missing a few fields w/Rabbit shipper.

### ISSUE THREAD

**Issue by cwmoriarty** [jprouty/mint-amazon-tagger#123]
Looks like Order CSV is missing a few fields ( Shipping Address Street 1 | Shipping Address Street 2 | Shipping Address City | Shipping Address State | Shipping Address Zip) when the shipper is "Rabbit"?

CSV snapshot:
<img width="906" alt="image" src="https://user-images.githubusercontent.com/1413232/206519268-a0ee2313-7af1-41ac-b1d7-007eefacbb69.png">

Unhandled error:
```
Error while parsing Amazon Order history report CSV files: 'Order' object has no attribute 'shipping_address_state'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mintamazontagger/tagger.py", line 55, in create_updates
    orders = amazon.Order.parse_from_csv(
  File "/usr/local/lib/python3.10/site-packages/mintamazontagger/amazon.py", line 246, in parse_from_csv
    return parse_from_csv_common(
  File "/usr/local/lib/python3.10/site-packages/mintamazontagger/amazon.py", line 95, in parse_from_csv_common
    result.append(cls(raw_dict))
  File "/usr/local/lib/python3.10/site-packages/mintamazontagger/amazon.py", line 240, in __init__
    if self.has_hidden_shipping_fee():
  File "/usr/local/lib/python3.10/site-packages/mintamazontagger/amazon.py", line 265, in has_hidden_shipping_fee
    self.shipping_address_state == 'CO'
AttributeError: 'Order' object has no attribute 'shipping_address_state'
Error while parsing Amazon Order history report CSV files: 'Order' object has no attribute 'shipping_address_state'
```

**Comment by jprouty** [comment]
Thanks for the report (and sorry for the delayed response). Can you share your CSV header row? I'm curious why "shipping_address_state" would be missing in your case (It's currently present for me).

**Comment by jprouty** [comment]
Gentle ping; curious if I can help you out with this issue. Thanks.
