### ISSUE TITLE
Amazon auth issue in 1.57

### ISSUE THREAD

**Issue by cwmoriarty** [jprouty/mint-amazon-tagger#128]
Two possibly related issues in 1.57, chrome109, osx

Currently getting stuck in a loop: 

<img width="869" alt="image" src="https://user-images.githubusercontent.com/1413232/212398977-5fa8023c-6106-4009-8315-fc0995185d60.png">

Workaround is to simply launch https://www.amazon.com/b2b/reports manually.
but then... tagger crashes a few seconds later.  Feels like "Refresh reports" should wait at least 30 seconds?

```
Login to Amazon.com successful
Requesting Items report
Requesting Orders report
Requesting Refunds report
Waiting for Items report to be ready
Clicking "Refresh Reports" button
Clicking "Refresh Reports" button



Traceback (most recent call last):
  File "/usr/local/bin/mint-amazon-tagger-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/mintamazontagger/cli.py", line 105, in main
    if not fetch_order_history(
  File "/usr/local/lib/python3.10/site-packages/mintamazontagger/orderhistory.py", line 152, in fetch_order_history
    if not wait_for_report(webdriver, report, progress_factory,
  File "/usr/local/lib/python3.10/site-packages/mintamazontagger/orderhistory.py", line 98, in wait_for_report
    refresh_button.click()
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 410, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=109.0.5414.87)
```

**Comment by jprouty** [comment]
Thanks for the report @cwmoriarty. I'm having a heck of a time getting 1.57 released :) I'm assuming you are using the PyPI version (via pip) as I haven't posted the 1.57 macOS release binary yet, correct?

**Comment by cwmoriarty** [comment]
Sorry to hear/appreciate the effort. That's correct.

**Comment by cwmoriarty** [comment]
Also please see some recommendations re StaleElementReferenceException:  https://stackoverflow.com/a/41502474

**Comment by jprouty** [comment]
Roger; Thanks for the pointer; the stale reference error is due to a poor implementation re: https://github.com/jprouty/mint-amazon-tagger/issues/118. I'll revise how that works for 1.58.

I'll look into the sign in flow as well.

In the meantime, if you wouldn't mind trying manually downloading the reports, and then plugging them in via csv file chooser, I'd be curious to know if the matching + tagging portion of the tool is working for you in 1.57. Thanks

**Comment by cwmoriarty** [comment]
<img width="857" alt="image" src="https://user-images.githubusercontent.com/1413232/212403931-3585cd1b-9938-4dfd-ac59-dc839f4fba5a.png">

selenium.common.exceptions.NoSuchWindowException: Message: no such window: No target with given id found


I should also mention that, having used Turbotax in the past--  there's evidence I have "two" intuit accounts for my one email address. I've always had to manually click through here, I think I raised a bug about this some time ago (figured it's rare scenario).
<img width="393" alt="image" src="https://user-images.githubusercontent.com/1413232/212404237-8500d177-50b3-4a2b-8603-74360a87af5b.png">

**Comment by cwmoriarty** [comment]
subsequent attempt:

```
Waiting for Mint Overview
Mint overview loaded


Getting Mint Categories\Getting Mint categories.
Getting Mint Categories|Traceback (most recent call last):
  File "/usr/local/bin/mint-amazon-tagger-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/mintamazontagger/cli.py", line 118, in main
    results = tagger.create_updates(
  File "/usr/local/lib/python3.10/site-packages/mintamazontagger/tagger.py", line 131, in create_updates
    mint_categories = mint_client.get_categories()
  File "/usr/local/lib/python3.10/site-packages/mintamazontagger/mintclient.py", line 115, in get_categories
    response = self.webdriver.request(
  File "/usr/local/lib/python3.10/site-packages/seleniumrequests/request.py", line 158, in request
    self.requests_session.headers = get_webdriver_request_headers(self, proxy_host=self.__proxy_host)
  File "/usr/local/lib/python3.10/site-packages/seleniumrequests/request.py", line 78, in get_webdriver_request_headers
    webdriver.switch_to.window(original_window_handle)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/switch_to.py", line 135, in window
    self._w3c_window(window_name)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/switch_to.py", line 143, in _w3c_window
    send_handle(window_name)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/switch_to.py", line 139, in send_handle
    self._driver.execute(Command.SWITCH_TO_WINDOW, {"handle": h})
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: received Inspector.detached event
  (Session info: chrome=109.0.5414.87)```

(Chrome window still open)

**Comment by jprouty** [comment]
The last error you received is due to an out of date dependency; I'll fix that by ensuring that pip enforces the right version of selenium-requests.

**Comment by jprouty** [comment]
Re: Multiple intuit accounts per same email - yes, this totally sucks! :) There's a command line arg (that also works for the gui) that can automate this: `--mint_intuit_account`. Manually clicking through any portions of the flow is harmless, so that's a fine workaround as well.

**Comment by jprouty** [comment]
Okay, I've replicated all of the issues you ran into (yay) and the mint one is not related to the multiple intuit account selector (although I'm sure you run into that as well). This issue is due to intuit changing their page layout and me using the wrong/stale selectors for the clicks we need. Stay tuned.

**Comment by jprouty** [comment]
Alright, please try again with version 1.58, live on PyPI (will also cut new release binaries too). Reopen if the issue persists.
