### ISSUE TITLE
Refresh logic too aggressive (1.59)

### ISSUE THREAD

**Issue by cwmoriarty** [jprouty/mint-amazon-tagger#131]
```
Waiting for Items report to be ready
Waiting for Items report to be ready.\Clicking "Refresh Reports" button
Waiting for Items report to be ready./Clicking "Refresh Reports" button
Waiting for Items report to be ready.|Clicking "Refresh Reports" button
Waiting for Items report to be ready.-Clicking "Refresh Reports" button
Waiting for Items report to be ready.|Clicking "Refresh Reports" button
Waiting for Items report to be ready./Clicking "Refresh Reports" button
Waiting for Items report to be ready./Clicking "Refresh Reports" button
Waiting for Items report to be ready./Traceback (most recent call last):
  File "/usr/local/bin/mint-amazon-tagger-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/mintamazontagger/cli.py", line 105, in main
    if not fetch_order_history(
  File "/usr/local/lib/python3.10/site-packages/mintamazontagger/orderhistory.py", line 158, in fetch_order_history
    if not wait_for_report(webdriver, report, progress_factory,
  File "/usr/local/lib/python3.10/site-packages/mintamazontagger/orderhistory.py", line 102, in wait_for_report
    refresh_button.click()
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 410, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a id="report-refresh-button" href="/b2b/reports">...</a> is not clickable at point (892, 571). Other element would receive the click: <html lang="en-us" class=" a-js a-audio a-video a-canvas a-svg a-drag-drop a-geolocation a-history a-webworker a-autofocus a-input-placeholder a-textarea-placeholder a-local-storage a-gradients a-hires a-transform3d a-touch-scrolling a-text-shadow a-text-stroke a-box-shadow a-border-radius a-border-image a-opacity a-transform a-transition a-ember" data-19ax5a9jf="dingo" data-aui-build-date="3.22.2-2023-01-13">...</html>
  (Session info: chrome=109.0.5414.87)
```

If this element is unreliable, maybe just reload the page yourself?

**Comment by jprouty** [comment]
Thanks for the report; I've reworked it again. Third time is a charm, right? :) Release is forthcoming.
