### ISSUE TITLE
Error logging into mint headless on v1.61 - unexpected keyword argument 'driver'

### ISSUE THREAD

**Issue by trumpetjh** [jprouty/mint-amazon-tagger#136]
Amazon login and file download works fine. Mint login fails every time. Error below.

Mint Login Flow: MintAPI to complete login
You may be asked for an auth code at the command line! Be sure to press ENTER after typing the 6 digit code.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/mint-amazon-tagger-cli", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mintamazontagger/cli.py", line 123, in main
    counter_progress_factory=counter_progress_cli)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mintamazontagger/tagger.py", line 123, in create_updates
    if not mint_client.login():
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mintamazontagger/mintclient.py", line 86, in login
    quit_driver_on_fail=False,
TypeError: __init__() got an unexpected keyword argument 'driver'

**Comment by jprouty** [comment]
Thanks for the report! I have a suspicion this is related to an old version of mintapi. I've updated the requirements/pypi deps to be more accurate. Please try again with 1.62 and report back if it persists, thanks.
