### ISSUE TITLE
'AttributeError: 'tuple' object has no attribute 'format'

### ISSUE THREAD

**Issue by noahsw** [jprouty/mint-amazon-tagger#15]
```
╰─± ./tagger.py /Users/noah/Downloads/01-Jan-2018_to_23-Mar-2018.csv  /Users/noah/Downloads/01-Jan-2018_to_23-Mar-2018\ \(1\).csv  --refunds /Users/noah/Downloads/01-Jan-2018_to_23-Mar-2018\ \(2\).csv  --no_tag_categories --mint_input_categories_filter=Shopping --mint_email hidden@hidden.com --dry_run
Dry Run; no modifications being sent to Mint.
Matching Amazon Items with Orders

Amazon Stats:

96 orders with 356 matching items
2 unmatched orders and 0 unmatched items
Orders ranging from 2017-12-31 to 2018-03-22
$3559.11 total spend
$36.32 avg order total (range: $5.27 - $237.82)
$9.77 avg item price (range: $0.33 - $237.82)

7 refunds dating from 2018-01-13 to 2018-02-06
$247.41 total refunded
Logging in via chromedriver
Login successful!
Creating Mint Category Map.
Fetching all Mint transactions since 12/31/17.
Got 616 transactions and 128 categories from Mint in 00:00:06
Backing up Mint Transactions prior to editing. Pickle epoch: 1521848325
Traceback (most recent call last):
  File "./tagger.py", line 679, in <module>
    main()
  File "./tagger.py", line 194, in main
    for r in refunds]
  File "./tagger.py", line 194, in <listcomp>
    for r in refunds]
  File "/Users/noah/Projects/mint-amazon-tagger/amazon.py", line 529, in to_mint_transaction
    note = self.get_note(),
  File "/Users/noah/Projects/mint-amazon-tagger/amazon.py", line 514, in get_note
    'Invoice url: {}').format(
AttributeError: 'tuple' object has no attribute 'format'
```

**Comment by noahsw** [comment]
Removing refunds works. Here's my refunds file:

[01-Jan-2018_to_23-Mar-2018 (2).xlsx](https://github.com/jprouty/mint-amazon-tagger/files/1843835/01-Jan-2018_to_23-Mar-2018.2.xlsx)

**Comment by jprouty** [comment]
Thanks for the report! It was an easy fix. Please try @HEAD and close to verify fix.

**Comment by jprouty** [comment]
FYI, I removed your refunds file.

**Comment by jprouty** [comment]
I'm assuming this is fixed now. Please re-open if that's not the case.
