### ISSUE TITLE
Internal error when processing zipfile with Amazon data

### ISSUE THREAD

**Issue by felciano** [jprouty/mint-amazon-tagger#156]
Just tried v1.65 with the zipfile from Amazon, and got the following in an error dialog box after clicking "Start Tagging": 
```
Error: Internal error while creating updates: Unknown string format: Due to technical 
limitations, please refer to your Order History (available in your Amazon account) for 
certain details about any orders placed prior to 2002
```
Any suggestions on how to resolve this?

**Comment by jprouty** [comment]
@felciano Sorry for the delay. I'm happy to try to debug this one last time. If you inspect your data export can you describe what you see in the files:
`Retail.OrderHistory.*/Retail.OrderHistory.*.csv`

I have a hunch that you may have multiple files and one of them starts with or only contains the said string you posted.

**Comment by jprouty** [comment]
Let me know if you still need help and we'll reopen. Thanks

**Comment by felciano** [comment]
Hi @jprouty sorry just getting back to this. The issue is still occurring. The source of the error is pretty clear: for transactions 2001-06-20 or earlier, the "Shipment Item Subtotal" and "Shipment Item Subtotal Tax" fields read "Due to technical limitations, please refer to your Order History (available in your Amazon account) for certain details about any orders placed prior to 2002".

Do you use these fields? If so, an easy fix most likely--especially given Mint's impending shutdown--is to give the user the option to ignore these records (or potentially just impose this as a limitation of the app overall).

**Comment by felciano** [comment]
FWIW, I've tried working around the error by:

- Unzipping the Amazon archive file
- Opening the order history CSV
- Deleting the rows that have that error value in one or both of those fields
- Saving the CSV back out
- Zipping everything back up, making sure to keep all the folders at the top level
- Importing the new zip archive into the app. 

This gets me to the point where the app imports the archive without error. I then log into Mint by hand, which seems to go successfully, and it goes through the "Getting Mint Transactions" step and starts "Parsing Mint Transactions".  I run into a new error:

```
'Transaction' object has no attribute 'description'
```
I can't tell if this is related to my surgery on the data files, or a separate issue--any thoughts? Log below.

```
2024-02-22 20:41:08,708 INFO mintamazontagger.mintclient: Mint Login Flow: login to be performed manually by the user
2024-02-22 20:41:44,879 INFO mintamazontagger.mintclient: Waiting for Mint Overview
2024-02-22 20:42:14,920 WARNING mintamazontagger.mintclient: Mint sync apparently incomplete after timeout. Data retrieved may not be current.
2024-02-22 20:42:14,921 INFO mintamazontagger.mintclient: Getting Mint categories.
2024-02-22 20:42:23,356 INFO mintamazontagger.mintclient: Getting all Mint transactions since 2001-08-14 to None.
2024-02-22 20:42:40,460 ERROR __main__: Internal error while creating updates: 'Transaction' object has no attribute 'description'
Traceback (most recent call last):
  File "mintamazontagger/main.py", line 624, in create_updates
  File "mintamazontagger/main.py", line 675, in do_create_updates
  File "mintamazontagger/tagger.py", line 177, in create_updates
  File "mintamazontagger/tagger.py", line 243, in get_mint_updates
  File "mintamazontagger/tagger.py", line 205, in get_mint_category_history_for_items
  File "mintamazontagger/tagger.py", line 206, in <listcomp>
  File "mintamazontagger/tagger.py", line 206, in <genexpr>
AttributeError: 'Transaction' object has no attribute 'description'
2024-02-22 20:42:40,552 ERROR __main__: Internal error while creating updates: 'Transaction' object has no attribute 'description'
2024-02-22 20:43:16,101 INFO __main__: Report Issue Clicked
```
