### ISSUE TITLE
Error: Internal error while creating updates

### ISSUE THREAD

**Issue by ovitch** [jprouty/mint-amazon-tagger#165]
Was running one of my last update on mint data before my switch. I've noticed a strange error (see picture). Tried both 1.65 and 1.66. 

Any idea => seems consistent across py files.

2024-03-19 16:22:58,443 INFO __main__: Running version 1.65
2024-03-19 16:22:58,777 WARNING __main__: Running out of date software is bad. Latest is 1.66
2024-03-19 16:23:16,466 INFO __main__: Creating a new webdriver
2024-03-19 16:23:17,076 INFO mintamazontagger.mintclient: Mint Login Flow: login to be performed manually by the user
2024-03-19 16:23:43,036 INFO mintamazontagger.mintclient: Waiting for Mint Overview
2024-03-19 16:23:45,928 INFO mintamazontagger.mintclient: Mint overview loaded
2024-03-19 16:23:45,928 INFO mintamazontagger.mintclient: Waiting for Mint to sync accounts
2024-03-19 16:23:48,603 INFO mintamazontagger.mintclient: Mint account sync complete
2024-03-19 16:23:48,603 INFO mintamazontagger.mintclient: Getting Mint categories.
2024-03-19 16:23:49,155 INFO mintamazontagger.mintclient: Getting all Mint transactions since 2009-05-01 to None.
2024-03-19 16:29:39,190 ERROR __main__: Internal error while creating updates: 
Traceback (most recent call last):
  File "mintamazontagger/main.py", line 626, in create_updates
  File "mintamazontagger/main.py", line 677, in do_create_updates
  File "mintamazontagger/tagger.py", line 177, in create_updates
  File "mintamazontagger/tagger.py", line 339, in get_mint_updates
AssertionError
2024-03-19 16:29:39,191 ERROR __main__: Internal error while creating updates: 
2024-03-19 16:33:04,145 INFO __main__: Report Issue Clicked

**Comment by ovitch** [comment]
So strange - Any idea? wondering if this is because of the big timeframe

2024-03-20 07:28:53,825 INFO __main__: Running version 1.66
2024-03-20 07:29:28,888 INFO __main__: Creating a new webdriver
2024-03-20 07:29:30,355 INFO mintamazontagger.mintclient: Mint Login Flow: login to be performed manually by the user
2024-03-20 07:29:54,452 INFO mintamazontagger.mintclient: Waiting for Mint Overview
2024-03-20 07:30:24,935 WARNING mintamazontagger.mintclient: Mint sync apparently incomplete after timeout. Data retrieved may not be current.
2024-03-20 07:30:24,936 INFO mintamazontagger.mintclient: Getting Mint categories.
2024-03-20 07:30:25,542 INFO mintamazontagger.mintclient: Getting all Mint transactions since 2009-05-01 to None.
2024-03-20 07:35:47,712 ERROR __main__: Internal error while creating updates: 
Traceback (most recent call last):
  File "mintamazontagger/main.py", line 624, in create_updates
  File "mintamazontagger/main.py", line 675, in do_create_updates
  File "mintamazontagger/tagger.py", line 177, in create_updates
  File "mintamazontagger/tagger.py", line 339, in get_mint_updates
AssertionError
2024-03-20 07:35:47,712 ERROR __main__: Internal error while creating updates: 
2024-03-20 07:36:14,387 INFO __main__: Report Issue Clicked
