### ISSUE TITLE
AttributeError: 'Refund' object has no attribute 'items'

### ISSUE THREAD

**Issue by noahsw** [jprouty/mint-amazon-tagger#29]
Flags used: `--print_unmatched --dry_run`

```
Traceback (most recent call last):
  File "/usr/local/bin/mint-amazon-tagger", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/main.py", line 149, in main
    print_unmatched(amazon.Order.merge(orders))
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/amazon.py", line 423, in merge
    result.set_items(Item.merge([i for o in orders for i in o.items]))
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/amazon.py", line 423, in <listcomp>
    result.set_items(Item.merge([i for o in orders for i in o.items]))
AttributeError: 'Refund' object has no attribute 'items'
```

**Comment by jprouty** [comment]
I'm a bit stumped on what might be causing this. It appears that a Refund object is making it down the Orders path, but that should not happen [is checked immediately before where you're having trouble].

**Comment by jprouty** [comment]
Just kidding! I found a reproduction case with some of my old transactions. I'll look closer

**Comment by jprouty** [comment]
Fixed and a new version is live

**Comment by noahsw** [comment]
Works great! Thanks for the speedy turnaround.
