### ISSUE TITLE
Crash when importing year 2018

### ISSUE THREAD

**Issue by aschmois** [jprouty/mint-amazon-tagger#30]
Trying to import all of amazon 2018 into Mint and when Mint finishes refreshing chrome crashes and an error is thrown:

```
You may be asked for an auth code at the command line! Be sure to press ENTER after typing the 6 digit code.
Get all Mint transactions since 11/11/16.
Traceback (most recent call last):
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Andres\AppData\Local\Programs\Python\Python37-32\Scripts\mint-amazon-tagger.exe\__main__.py", line 9, in <module>
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\site-packages\mintamazontagger\main.py", line 136, in main
    mint_category_name_to_id)
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\site-packages\mintamazontagger\tagger.py", line 100, in get_mint_updates
    amazon.associate_items_with_orders(orders, items, itemProgress)
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\site-packages\mintamazontagger\amazon.py", line 183, in associate_items_with_orders
    with timeout(1, exception=RuntimeError):
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\site-packages\interruptingcow\__init__.py", line 148, in __enter__
    return super(Timeout, self).__enter__()
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\site-packages\interruptingcow\compat.py", line 14, in __enter__
    return self.gen.__next__()
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\site-packages\interruptingcow\__init__.py", line 97, in timeout
    set_sighandler()
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\site-packages\interruptingcow\__init__.py", line 77, in set_sighandler
    current = signal.getsignal(signal.SIGALRM)
AttributeError: module 'signal' has no attribute 'SIGALRM'
```

These reports were downloaded by hand as the downloader fails at it. Running the last 90 days has no problem.

**Comment by jprouty** [comment]
Hi Andres! Thanks for all the issue reports.

It looks like you're running into a problem with interruptingcow (one of the libraries this project uses). It seems that Windows/Cygwin doesn't have the SIGALRM signal. Honestly, I'm a bit surprised this library doesn't handle/have a work around for this case.

Let me dig a bit more for a work around and get back to you. Just to verify, it looks like you are using Windows, Python 3.7. Are you also using cygwin? Or just standard python?

As a work around, you can try [temporarily commenting this section out](https://github.com/jprouty/mint-amazon-tagger/commit/da40bfd6722f26aed0bc8e150cfca1d4008e98c4#diff-6357bc7fecadb6b17a58eed04753c32d) in file: 
c:\users\andres\appdata\local\programs\python\python37-32\lib\site-packages\mintamazontagger\amazon.py

Be sure to revert the file before making your next update (not sure how pip likes it when you modify src under the hood!)

**Comment by aschmois** [comment]
Yeah sorry I'm using Windows 10 Python 3.7 downloaded directly from their site. I do run it on Git Bash but that's just ease of use rather than anything.

**Comment by jprouty** [comment]
Okay, I think I have a fix in. Please verify when you have a chance after pulling version 1.10 or later. I'll close for now, please reopen if it still persists!

**Comment by aschmois** [comment]
This one is still a no go. The program no longer crashes but it gets to Mint, logs in, waits for refresh, then says "Get all Mint transactions since 11/11/16." and nothing happens. Does not look like the program is doing anything. I let it run for a little while but Mint logged off.

**Comment by jprouty** [comment]
Hmm, just to verify, it sounds like this is a separate issue (ie, the original issue is fixed, and now you're hitting something else).

Can you try:

1. Look for the folder: "Mint Backup" inside your current directory. Note if it's missing
2. Run `dir '.\Mint Backup\'` or `ls` (Same thing in powershell)
3. Run the script as you were before, making sure you 
4. Run (2) again, and compare the difference. If there's a new set of files, then it did fetch all the transactions. If it completely hangs, there should be no new files (or even no directory!)

**Comment by jprouty** [comment]
@aschmois Please try updating past 1.12 and see if that works... and if not, try the above steps to help debug. Thanks!

**Comment by jprouty** [comment]
@aschmois Closing this assuming that was indeed the fix. Please reopen if you're still struggling! Thanks
