### ISSUE TITLE
Crash when supplying date

### ISSUE THREAD

**Issue by aschmois** [jprouty/mint-amazon-tagger#31]
When using --order_history_start_date "2018-01-01" --order_history_num_days "356" I get this error: (Windows)

```
Traceback (most recent call last):
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Andres\AppData\Local\Programs\Python\Python37-32\Scripts\mint-amazon-tagger.exe\__main__.py", line 9, in <module>
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\site-packages\mintamazontagger\main.py", line 40, in main
    args = parser.parse_args()
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\argparse.py", line 1749, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\argparse.py", line 1781, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\argparse.py", line 1987, in _parse_known_args
    start_index = consume_optional(start_index)
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\argparse.py", line 1927, in consume_optional
    take_action(action, args, option_string)
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\argparse.py", line 1839, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\argparse.py", line 2369, in _get_values
    value = self._get_value(action, arg_string)
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\argparse.py", line 2402, in _get_value
    result = type_func(arg_string)
  File "c:\users\andres\appdata\local\programs\python\python37-32\lib\site-packages\mintamazontagger\main.py", line 325, in <lambda>
    type=lambda s: datetime.date.strptime(s, '%Y-%m-%d'),
AttributeError: type object 'datetime.date' has no attribute 'strptime'
```

**Comment by jprouty** [comment]
Thanks! This is an easy fix! Stay tuned.

**Comment by jprouty** [comment]
Fix out!

**Comment by aschmois** [comment]
Issue fixed confirmed!
