### ISSUE TITLE
Error on collecting mint data

### ISSUE THREAD

**Issue by JoeNVF** [jprouty/mint-amazon-tagger#33]
Get all Mint transactions since 08/27/18.
Fetching Transactions -
Backing up Mint to local pickle file, epoch: 1550958058 \Traceback (most recent call last):
  File "/home/X/.local/bin/mint-amazon-tagger", line 11, in <module>
    sys.exit(main())
  File "/home/X/.local/lib/python3.6/site-packages/mintamazontagger/main.py", line 131, in main
    args.mint_pickle_location)
  File "/home/X/.local/lib/python3.6/site-packages/mintamazontagger/main.py", line 297, in dump_trans_and_categories
    with open(trans_pickle_path, 'wb', encoding='utf-8') as f:
ValueError: binary mode doesn't take an encoding argument

Mint Backup is empty.  Kunbuntu 18.10

**Comment by jprouty** [comment]
Whoops. My bad. Fixed. Please update to version 1.12 or later!
