### ISSUE TITLE
Error During Init - session_path

### ISSUE THREAD

**Issue by LC1207** [jprouty/mint-amazon-tagger#39]
Seeing the following error when it tries to log into Mint:

```
Traceback (most recent call last):
  File "/usr/local/bin/mint-amazon-tagger", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/main.py", line 124, in main
    mint_category_name_to_id = mint_client.get_categories()
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/mintclient.py", line 70, in get_categories
    mint_api = self.get_mintapi()
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/mintclient.py", line 56, in get_mintapi
    headless=self.headless)
  File "/usr/local/lib/python3.7/site-packages/mintapi/api.py", line 209, in create
    return Mint(email, password, **opts)
TypeError: __init__() got an unexpected keyword argument 'session_path'
```

Is this a known issue? Anyone seen this before?

**Comment by jprouty** [comment]
Hello! It looks like you have an old version of mintapi. I would recommend:
pip install --upgrade mintapi mint-amazon-tagger

**Comment by jprouty** [comment]
After you've done that, please report back. If it's still not working, please verify your versions and post here: `pip list | grep mint`

**Comment by LC1207** [comment]
@jprouty thank you for the response. that fixed it!
