### ISSUE TITLE
Mint website changed

### ISSUE THREAD

**Issue by djdaniels90** [jprouty/mint-amazon-tagger#40]
Selenium is hanging upon going to the mint page.  I believe this is due to the structure of the page being altered recently.  I'l submit a fix for this in a few days when i have time, but it should be pretty easy to find the correct dom target.

**Comment by djdaniels90** [comment]
```
You may be asked for an auth code at the command line! Be sure to press ENTER after typing the 6 digit code.
Traceback (most recent call last):
  File "/Users/djdaniels/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mintapi/api.py", line 215, in get_web_driver
    element = driver.find_element_by_link_text("Log In")
  File "/Users/djdaniels/.pyenv/versions/3.7.3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/Users/djdaniels/.pyenv/versions/3.7.3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/djdaniels/.pyenv/versions/3.7.3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/djdaniels/.pyenv/versions/3.7.3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Log In"}
  (Session info: chrome=75.0.3770.100)
  (Driver info: chromedriver=2.41.578706 (5f725d1b4f0a4acbf5259df887244095596231db),platform=Mac OS X 10.14.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/djdaniels/.pyenv/versions/3.7.3/bin/mint-amazon-tagger", line 10, in <module>
    sys.exit(main())
  File "/Users/djdaniels/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mintamazontagger/main.py", line 124, in main
    mint_category_name_to_id = mint_client.get_categories()
  File "/Users/djdaniels/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mintamazontagger/mintclient.py", line 70, in get_categories
    mint_api = self.get_mintapi()
  File "/Users/djdaniels/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mintamazontagger/mintclient.py", line 56, in get_mintapi
    headless=self.headless)
  File "/Users/djdaniels/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mintapi/api.py", line 346, in create
    return Mint(email, password, **opts)
  File "/Users/djdaniels/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mintapi/api.py", line 342, in __init__
    imap_folder=imap_folder)
  File "/Users/djdaniels/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mintapi/api.py", line 426, in login_and_get_token
    imap_folder=imap_folder)
  File "/Users/djdaniels/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mintapi/api.py", line 219, in get_web_driver
    element = driver.find_element_by_link_text("LOG IN")
  File "/Users/djdaniels/.pyenv/versions/3.7.3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/Users/djdaniels/.pyenv/versions/3.7.3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/djdaniels/.pyenv/versions/3.7.3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/djdaniels/.pyenv/versions/3.7.3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"LOG IN"}
  (Session info: chrome=75.0.3770.100)
  (Driver info: chromedriver=2.41.578706 (5f725d1b4f0a4acbf5259df887244095596231db),platform=Mac OS X 10.14.5 x86_64)

```

**Comment by fatshred** [comment]
It looks like the Log in text changed to Sign In.

**Comment by djdaniels90** [comment]
Ya, that simple change should do it, i'l probably get to it this weekend or so.

**Comment by jprouty** [comment]
Looks like this is already fixed upstream in MintAPI but waiting for a new package version w/ the fix. When the update is pushed to pypi, you can update w/
python -m pip install mint-amazon-tagger --upgrade

See:
https://github.com/mrooney/mintapi/commit/3b83fc7ca3a46b183f46b39171e48652a39d889e
