### ISSUE TITLE
chromedriver leaves browser open, causing subsequent runs to fail

### ISSUE THREAD

**Issue by cwmoriarty** [jprouty/mint-amazon-tagger#46]
Chrome test mode window appears, with the below error in the console.

I ran once and logged into Amazon in the browser (missing the CLI password prompt), subsequent runs produce:

```
Missing Items/Orders History csv. Attempting to fetch from Amazon.com.
Logging into Amazon.com
Traceback (most recent call last):
  File "/usr/local/bin/mint-amazon-tagger", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/main.py", line 76, in main
    session_path, args.headless)
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/orderhistory.py", line 64, in fetch_order_history
    session_path=session_path)
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/orderhistory.py", line 168, in get_amzn_driver
    executable_path=executable_path)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /Applications/Google Chrome.app/Contents/MacOS/Google Chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.41.578706 (5f725d1b4f0a4acbf5259df887244095596231db),platform=Mac OS X 10.14.6 x86_64)


```

**Comment by jprouty** [comment]
Try closing the last chrome window. Sometimes, on a mac especially, it can leave a dangling Chrome instance that inferrers with future runs.

**Comment by jprouty** [comment]
Great! There might be a way to catch this/ensure no dangling browsers are left open. I'll take a look to see if there's anything to make this more robust.

**Comment by jprouty** [comment]
I've added a little extra atexit logic to help. For my personal reference later, just in case, there's some options to kill by pid/etc if we want to be extra careful. However, it seems that the main culprit would be non-clean exits/errors in the program.

https://stackoverflow.com/questions/10752512/get-pid-of-browser-launched-by-selenium
