### ISSUE TITLE
ModuleNotFoundError: No module named 'seleniumrequests'

### ISSUE THREAD

**Issue by davidlday** [jprouty/mint-amazon-tagger#5]
I get the following error when trying to run in a virtual environment:
```
(mint-amazon-tagger) 
dday@thinker:~/github/mint-amazon-tagger (master=)
$ ./tagger.py ~/Documents/Items\ -\ 11-2017\ -\ David.csv ~/Documents/Orders\ -\ 11-2017\ -\ David.csv --refunds ~/Documents/Refunds\ -\ 11-2017\ -\ David.csv --dry_run --mint_email dday376@gmail.com
Traceback (most recent call last):
  File "./tagger.py", line 27, in <module>
    from mintapifuture.mintapi.api import Mint, MINT_ROOT_URL
  File "/home/dday/github/mint-amazon-tagger/mintapifuture/mintapi/__init__.py", line 1, in <module>
    from .api import Mint
  File "/home/dday/github/mint-amazon-tagger/mintapifuture/mintapi/api.py", line 14, in <module>
    from seleniumrequests import Chrome
ModuleNotFoundError: No module named 'seleniumrequests'
```

Running on Ubuntu 17.10.
```
(mint-amazon-tagger) 
dday@thinker:~/github/mint-amazon-tagger (master=)
$ python --version
Python 3.6.3

(mint-amazon-tagger) 
dday@thinker:~/github/mint-amazon-tagger (master=)
$ pip --version
pip 9.0.1 from /home/dday/.virtualenvs/mint-amazon-tagger/lib/python3.6/site-packages (python 3.6)

(mint-amazon-tagger) 
dday@thinker:~/github/mint-amazon-tagger (master=)
$ pip list
Package       Version  
------------- ---------
asn1crypto    0.24.0   
certifi       2017.11.5
cffi          1.11.2   
chardet       3.0.4    
chromedriver  2.24.1   
cryptography  2.1.4    
idna          2.6      
keyring       10.5.1   
mintapi       1.28     
pip           9.0.1    
pkg-resources 0.0.0    
pycparser     2.18     
readchar      0.7      
requests      2.18.4   
SecretStorage 2.3.1    
selenium      3.8.0    
setuptools    38.2.5   
six           1.11.0   
urllib3       1.22     
wheel         0.30.0   
xmltodict     0.11.0  

(mint-amazon-tagger) 
dday@thinker:~/github/mint-amazon-tagger (master=)
$ sudo apt search chromedriver
Sorting... Done
Full Text Search... Done
chromium-chromedriver/artful-updates,artful-security,now 63.0.3239.84-0ubuntu0.17.10.1 amd64 [installed]
  WebDriver driver for the Chromium Browser

```

I wound up doing a ```pip install selenium-requests``` and got a little further, but may need to open a second issue.. Perhaps selenium-requests needs added to the requirements.txt?

I also have a Mac I can try this on later.

**Comment by jprouty** [comment]
Whoops! You are most certainly correct :) Please try again and we'll go from there. Closing assuming that was the fix. Feel free to reopen.

**Comment by davidlday** [comment]
Just a quick follow-up on this. I tested on Mac, and installing selenium also installed selenium-requests, so not sure what's up there. However, I had to also manually install xmltodict for some weird reason. Worked as expected after that. Here are the details from my Mac (OSX High Sierra):

```
(mint-amazon-tagger) 
dday@cthulhu:~/Projects/mint-amazon-tagger (master %=)
$ python --version
Python 3.6.4

(mint-amazon-tagger) 
dday@cthulhu:~/Projects/mint-amazon-tagger (master %=)
$ pip --version
pip 9.0.1 from /Users/dday/.virtualenvs/mint-amazon-tagger/lib/python3.6/site-packages (python 3.6)

(mint-amazon-tagger) 
dday@cthulhu:~/Projects/mint-amazon-tagger (master %=)
$ pip list
Package           Version  
----------------- ---------
certifi           2017.11.5
chardet           3.0.4    
chromedriver      2.24.1   
idna              2.6      
keyring           10.5.1   
pip               9.0.1    
readchar          0.7      
requests          2.18.4   
requests-file     1.4.2    
selenium          3.8.0    
selenium-requests 1.3      
setuptools        38.2.5   
six               1.11.0   
tldextract        2.2.0    
urllib3           1.22     
wheel             0.30.0   
xmltodict         0.11.0   
```
