### ISSUE TITLE
Better errors for empty CSV files

### ISSUE THREAD

**Issue by glassdimly** [jprouty/mint-amazon-tagger#51]
While downloading files from Amazon, I noticed my "Items" is `0 bytes`. Apparently something is wrong over there in Bezos-land, because even a previously-downloaded date range produces a `0 bytes` `csv`.

<img width="426" alt="image" src="https://user-images.githubusercontent.com/1361104/71458254-7c5ff680-2767-11ea-9d9e-0b12c0bcc317.png">

Given that this happened to me, I assume it will happen to others.

However, the error I get is: 
```
Parsing Orders - 343
Parsing Items - Traceback (most recent call last):
  File "/Users/jeremy/bin/mint-amazon-tagger/mintamazontagger/main.py", line 499, in <module>
    main()
  File "/Users/jeremy/bin/mint-amazon-tagger/mintamazontagger/main.py", line 86, in main
    items_csv, ProgressCounter('Parsing Items - '))
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/amazon.py", line 453, in parse_from_csv
    return parse_from_csv_common(cls, csv_file, progress)
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/amazon.py", line 75, in parse_from_csv_common
    if is_empty_csv(csv_file):
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/amazon.py", line 71, in is_empty_csv
    open(filename, encoding='utf-8')))[key] is None)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/csv.py", line 112, in __next__
    row = next(self.reader)
StopIteration
```

So it's clear that this isn't a bug in `mint-amazon-tagger`, a friendlier error might be warranted, no? For instance: `The Items report at my/file/location.csv contains no data. Try downloading again directly from [amazon reports URL]`.

**Comment by jprouty** [comment]
Thanks for the feedback! Absolutely better messaging should be giving. The blank csv is new; amazon used to be giving: "No data found for this time period" instead, which was super nuisance since it's technically a csv, but not really :-P.

I have a fix that will be released shortly. Thanks!
