### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 84

### ISSUE THREAD

**Issue by danwenzel** [jprouty/mint-amazon-tagger#64]
Using macOS Mojave 10.14.6

Upgraded to the latest version of mint-amazon-tagger (1.30)

After running the `mint-amazon-tagger` command in the terminal, entering my credentials, and pressing "Start Tagging", getting this popup:

![image](https://user-images.githubusercontent.com/11724146/87857867-90c83400-c8ef-11ea-913c-c5c1307203d2.png)

The full error log:

```
$ mint-amazon-tagger
Logging into Amazon.com
Internal error while creating updates: Message: session not created: This version of ChromeDriver only supports Chrome version 84
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/main.py", line 607, in create_updates
    self.do_create_updates(args, parent)
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/main.py", line 651, in do_create_updates
    counter_progress_factory=progress_factory)
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/tagger.py", line 64, in create_updates
    progress_factory=indeterminate_progress_factory)
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/orderhistory.py", line 63, in fetch_order_history
    session_path=session_path)
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/orderhistory.py", line 144, in get_amzn_driver
    os.getcwd()))
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 84

Internal error while creating updates: Message: session not created: This version of ChromeDriver only supports Chrome version 84
```

**Comment by jprouty** [comment]
Hi Dan. This almost certainly means you have an out of date chrome version.
Please update to 84 or later.

**Comment by danwenzel** [comment]
Thanks, @jprouty - Upgrading my local chrome version to 84 worked.

I had thought that selenium was using its own, separate version of chrome... 🤷‍♂️

**Comment by jprouty** [comment]
It's a rather confusing setup TBH! We (this project and the mintapi underlying project) changed how it works recently, so a more recent version of Chromedriver is used (the thing that bridges the gap between this project's code and chrome itself). For things to run smoothly, you'll need the current stable version of chrome/chromium.

Be well!
