### ISSUE TITLE
Error Logging Into Amazon

### ISSUE THREAD

**Issue by LC1207** [jprouty/mint-amazon-tagger#70]
I've updated via pip and am running Chrome v89.0.4389.90. The Tagger fails at Amazon login step. There is no "Remember Me" checkbox and it throws an error as it looks for that element. Has anyone else run into this?

```
Logging into Amazon.com
Internal error while creating updates: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="rememberMe"]"}
  (Session info: chrome=89.0.4389.90)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/main.py", line 607, in create_updates
    self.do_create_updates(args, parent)
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/main.py", line 651, in do_create_updates
    counter_progress_factory=progress_factory)
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/tagger.py", line 64, in create_updates
    progress_factory=indeterminate_progress_factory)
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/orderhistory.py", line 64, in fetch_order_history
    session_path=session_path)
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/orderhistory.py", line 178, in get_amzn_driver
    driver.find_element_by_name('rememberMe').click()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 496, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="rememberMe"]"}
  (Session info: chrome=89.0.4389.90)

Internal error while creating updates: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="rememberMe"]"}
  (Session info: chrome=89.0.4389.90)
```

**Comment by jprouty** [comment]
Thanks for the report! I'll take a look shortly (Sounds like Amazon changed some UI layout/names).

**Comment by LC1207** [comment]
Tried it again today and no error. ¯\_(ツ)_/¯
