### ISSUE TITLE
Error parsing tax

### ISSUE THREAD

**Issue by tigretigre** [jprouty/mint-amazon-tagger#73]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mintamazontagger/main.py", line 607, in create_updates
    self.do_create_updates(args, parent)
  File "/usr/local/lib/python3.9/site-packages/mintamazontagger/main.py", line 646, in do_create_updates
    results = tagger.create_updates(
  File "/usr/local/lib/python3.9/site-packages/mintamazontagger/tagger.py", line 173, in create_updates
    updates, unmatched_orders = get_mint_updates(
  File "/usr/local/lib/python3.9/site-packages/mintamazontagger/tagger.py", line 353, in get_mint_updates
    if order.attribute_itemized_diff_to_per_item_tax():
  File "/usr/local/lib/python3.9/site-packages/mintamazontagger/amazon.py", line 364, in attribute_itemized_diff_to_per_item_tax
    self.items[adjust_idx].item_subtotal_tax += adjust_amount
TypeError: list indices must be integers or slices, not NoneType
Internal error while creating updates: list indices must be integers or slices, not NoneType
```

**Comment by jprouty** [comment]
Thank you for the post; this is a rather odd edge case that I believe I have a fix for. My best guess is that you have an order with item(s) that have no sales tax, but the order itself has tax; the tagger needs to reconcile this difference somehow otherwise the itemizing logic falls apart. This is the only case I can think of that would fail in the way posted above.

I have pushed the fix and a new version is out as 1.34. I am working on the prebuilt binaries. Please reopen if this happens again when using 1.34!
