### ISSUE TITLE
Mint: element is not attached to the page document

### ISSUE THREAD

**Issue by kwylie** [jprouty/mint-amazon-tagger#74]
After being presented with the Mint / Intuit logic screen and entering the SMS verification code (and pressing Enter), I get the following error message.

```
Name: mint-amazon-tagger
Version: 1.34
```

```
You may be asked for an auth code at the command line! Be sure to press ENTER after typing the 6 digit code.
Logging into Mint|Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/mint-amazon-tagger-cli", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mintamazontagger/cli.py", line 77, in main
    counter_progress_factory=counter_progress_cli)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mintamazontagger/tagger.py", line 148, in create_updates
    mint_category_name_to_id = mint_client.get_categories()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mintamazontagger/mintclient.py", line 85, in get_categories
    mint_api = self.get_mintapi()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mintamazontagger/mintclient.py", line 70, in get_mintapi
    chromedriver_download_path=home_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mintamazontagger/api.py", line 500, in create
    return Mint(email, password, **opts)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mintamazontagger/api.py", line 496, in __init__
    chromedriver_download_path=chromedriver_download_path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mintamazontagger/api.py", line 584, in login_and_get_token
    chromedriver_download_path=chromedriver_download_path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mintamazontagger/api.py", line 403, in get_web_driver
    imap_password, imap_server, imap_folder)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mintamazontagger/api.py", line 312, in _sign_in
    email_input.clear()  # clear email and user specified email
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 95, in clear
    self._execute(Command.CLEAR_ELEMENT)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=90.0.4430.212)
```

**Comment by jprouty** [comment]
Hi @kwylie, A quick workaround is to follow the login flow in the browser and get through the signin process manually. Then try running the application again. It should skip 2FA/SMS verification on the second attempt after a successful login.

**Comment by kwylie** [comment]
I've tried this several times, and I'm forced to do the 2FA/SMS verification every single time.  Not sure if this is a change on Intuit's side or not.  Let me know if there's anything I can do to help test.

**Comment by danlitwin** [comment]
I believe Mint's login pages might have changed.  Same problem as @kwylie with the same errors, and then I have to hit Ctrl-Break because the script never stops running.

**Comment by kwylie** [comment]
I think it's related to [this issue](https://github.com/mrooney/mintapi/issues/259) in `mintapi`

**Comment by hudcap** [comment]
No idea what this repo is lol, but it looks like this issue might be fixed with https://github.com/mrooney/mintapi/pull/260
It fixed the issue in the previous post for me and it would be great to see if it works for others too.

**Comment by jprouty** [comment]
Thanks, yes, that was likely the issue. I just cut version 1.35 and am releasing that version now. Please try that and reopen if you continue to have issues.

**Comment by kwylie** [comment]
Hmmm... having this issue again, on v1.35.  Any ideas?
